application: appname
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webob
  version: latest
- name: markupsafe
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /_ah/task/.*
  script: task.app
  login: admin

- url: /service/.*
  script: service.app
  login: required

- url: .*
  script: main.app
  login: required

